version: "3"
services:
  languagetool:
    image: erikvl87/languagetool
    container_name: languagetool_server
    ports:
        - 8010:8010
    environment:
        - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
        - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
        - Java_Xmx=1g  # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
        - ~/.ngrams:/ngrams

  cors:
    build: nginx/.
    container_name: languagetool_cors
    ports:
      - 8081:8081
